# Generated by Django 5.2.1 on 2025-05-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sazonalidade", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("senha", models.CharField(max_length=100)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=200)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("produtos", models.ManyToManyField(to="recomendacao.produto")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comentario", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "produtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recomendacao.produtor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recomendacao.usuario",
                    ),
                ),
            ],
        ),
    ]
